stages:
  - test
  - name: deploy
    if: branch = master AND NOT type = cron

language: node_js

node_js:
  - lts/*

jobs:
  include:
    - stage: test
      before_script: lerna exec --ignore '@multicycles/{front,developer}' -- npm i
      script: npm test

    - stage: deploy
      install: skip
      services:
        - docker
      script:
        - sh build.sh
      after_success:
        - sh push.sh

notifications:
  email:
    on_success: never
    on_failure: always
